services:
    sonata.admin.issues:
        class: Zertz\BugBundle\Admin\BugAdmin
        arguments: [null, Zertz\BugBundle\Entity\Bug, 'SonataAdminBundle:CRUD']
        calls:
            - [setTranslationDomain, [Zertz\BugBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Issues, label: Issues }
